<?php

/*
 * Implements hook_menu()
 */

function menu_magic_menu() {
  $items = array();

  $items['magic'] = array(
    'title' => 'A little magic', //titles will be translated automatically
    'page callback' => 'menu_magic_basic',
    'access callback' => 'user_access', // user_access is defined by drupal core.  this is called by default but the paramaters below are necessary
    'access arguments' => array('access content')  // this argument is passed the the user_access function
  );

  $items['magic/%'] = array(
    'title' => 'Even more magic', //titles will be translated automatically
    'page callback' => 'menu_magic_extra',
    'page arguments' => array(1),
    'access arguments' => array('access content'), // this argument is passed the the user_access function
    'file' => 'menu_magic_extra.inc',
  );

  $items['user/%/magic'] = array(
    'title' => 'Magic',
    'description' => 'Magical magic for users',
    'page callback' => 'menu_magic_user_tab',
    'page arguments' => array(1),
    'access callback' => 'user_access', // user_access is defined by drupal core.  this is called by default but the paramaters below are necessary
    'access arguments' => array('access content'), // this argument is passed the the user_access function
    'file' => 'menu_magic.user.inc',
    'type' => MENU_LOCAL_TASK, //type is used to determine what type of menu this is
  );

  $items['node/%node/magic'] = array(
    'title' => 'Magic', //titles will be translated automatically
    'page callback' => 'menu_magic_node_context',
    'page arguments' => array(1),
    'access arguments' => array('access content'), // this argument is passed the the user_access function
    'file' => 'menu_magic.context.inc',
    'type' => MENU_LOCAL_TASK,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
  );

  return $items;
}

function menu_magic_basic() {
  $content = array();
  $content['raw_markup'] = array(
    '#type' => 'markup',
    '#markup' => 'Truly, this is magical!',
    '#prefix' => '<p>',
    '#sufix' => '</p>'
  );

  $variables = array(
    'path' => 'http://placekitten.com/440/400',
    'alt' => t('This is a magical kitten'),
    'title' => t('This is the title')
  );

  $content['themed_data'] = array(
    '#type' => 'markup',
    '#markup' => theme('image', $variables),
    '#prefix' => '<div class="menu-magic-image">',
    '#sufix' => '</div>',
    '#attached' => array(
      'css' => array(
        drupal_get_path('module', 'menu_magic') . '/menu-magic.css'
      )
    ),
  );

  $content['renderable_element'] = array(
    '#theme' => 'item_list',
    '#title' => t('How do we know it\'s magic?'),
    '#items' => array(
      t('item 1'),
      t('item 2'),
      t('item 3'),
      t('The current time is %time', array('%time' => date('r'))),
    ),
    '#cache' => array(
      'keys' => array('menu_magic', 'renderable_element'),
      'bin' => 'cache',
      'expire' => time() + 10,
      'granularity' => DRUPAL_CACHE_PER_PAGE
    ),
  );

  return $content;
}
